<section class="track" aria-labelledby="track-title" aria-describedby="track-desc">
    <div class="shadow-top" aria-hidden="true"></div>

    <header class="track__header">
        <div class="track__header--wrap">
            <p class="track__tooltip">Track Record</p>
            <h2 class="track__title" id="track-title">
                A Track Record <br> Of Strong Fund Performance
            </h2>
        </div>
        <p class="track__desc" id="track-desc">
            Our fund has a consistent record of strong returns. Each sector contributes to sustainable, long-term growth.
        </p>
    </header>

    <div class="track__footer" role="region" aria-roledescription="carousel" aria-label="Track record slides">
        <ul class="track__list" role="list">
            <li class="track__item active" data-slide="1" id="track-slide-1" aria-hidden="false">
                <article class="track__card" aria-labelledby="track-slide-1-title">
                    <div class="track__card--wrap">
                        <div
                            class="progress-bar"
                            data-percentage="54"
                            role="img"
                            aria-label="54 percent of total income">
                            <div class="progress-bar__circle" aria-hidden="true">
                                <div class="progress-bar__circle-fill"></div>
                                <div class="progress-bar__circle-inner">
                                    <div class="progress-bar__glow"></div>
                                </div>
                            </div>
                            <div class="progress-bar__text" aria-hidden="true">54%</div>
                        </div>

                        <div class="track__card--info">
                            <h3 class="track__card--title" id="track-slide-1-title">
                                Cryptocurrency Mining: Stability and Transparency
                            </h3>
                            <p class="track__card--desc">Cryptocurrency mining is our core business and we consider
                                it
                                one of the most stable and reliable businesses in the world of cryptocurrencies.
                                Unlike
                                trading, which is subject to high risks and fluctuations, mining allows for a stable
                                and
                                predictable income. We have created all the necessary conditions for efficient and
                                comfortable mining, which makes it the main source of our profit - 54% of our total
                                income.</p>
                            <p class="track__card--desc">Our experience in mining started in 2019, when we installed
                                the
                                first 10,000 miners, and since then we have continued to actively develop this
                                business.
                                We provide our partners with full control and transparency of processes: everyone
                                can
                                monitor the activity of our mining farm in real time.</p>
                        </div>
                    </div>
                </article>
            </li>

            <li class="track__item" data-slide="2" id="track-slide-2" aria-hidden="true">
                <article class="track__card" aria-labelledby="track-slide-2-title">
                    <div class="track__card--wrap">
                        <div class="progress-bar" data-percentage="10" role="img" aria-label="10 percent of total income">
                            <div class="progress-bar__circle" aria-hidden="true">
                                <div class="progress-bar__circle-fill"></div>
                                <div class="progress-bar__circle-inner">
                                    <div class="progress-bar__glow"></div>
                                </div>
                            </div>
                            <div class="progress-bar__text" aria-hidden="true">10%</div>
                        </div>

                        <div class="track__card--info">
                            <h3 class="track__card--title" id="track-slide-2-title">Selling Heat from Mining: New Income Source</h3>
                            <p class="track__card--desc">Not many people know, but the excess heat generated by mining
                                farms can be used for commercial purposes. While most farmers use this heat for space
                                heating and some don't even pay attention to it, we have found a way to turn excess heat
                                into an additional source of income.</p>
                            <p class="track__card--desc">With the help of our technologists, we have developed a
                                business model that allows us to sell the heat generated by the miners. This line of
                                business already brings us up to 10% profit from the total turnover of mining assets.
                            </p>
                            <p class="track__card--desc title">How does it work?</p>
                            <p class="track__card--desc">If we consume 50 MW of electricity (corresponding to about
                                1,000 miners), the excess heat of 5 MW can be effectively utilised for sale. We sell
                                this heat at market electricity prices, making a profit of up to 10% of turnover.
                                This is an area of active development and we plan to expand it further to maximise all
                                opportunities to increase profitability and improve our financial stability.</p>
                        </div>
                    </div>
                </article>
            </li>

            <li class="track__item" data-slide="3" id="track-slide-3" aria-hidden="true">
                <article class="track__card" aria-labelledby="track-slide-3-title">
                    <div class="track__card--wrap">
                        <div class="progress-bar" data-percentage="6" role="img" aria-label="6 percent of total income">
                            <div class="progress-bar__circle" aria-hidden="true">
                                <div class="progress-bar__circle-fill"></div>
                                <div class="progress-bar__circle-inner">
                                    <div class="progress-bar__glow"></div>
                                </div>
                            </div>
                            <div class="progress-bar__text" aria-hidden="true">6%</div>
                        </div>

                        <div class="track__card--info">
                            <h3 class="track__card--title" id="track-slide-3-title">Sell patented technologies for hash rate increase: start successful mining business</h3>
                            <p class="track__card--desc">We offer unique patented hash rate boosting technologies to
                                help companies and individuals upgrade and optimise their mining operations. If you're
                                looking to start a cryptocurrency mining business, we know how to help you maximise your
                                profits.</p>
                            <p class="track__card--desc">Our advanced solutions, including technology, software, hosting
                                and business strategies, allow you to significantly improve the efficiency of your
                                mining processes and achieve high financial results. We are ready to share with you our
                                experience and secrets of successful business in the cryptocurrency industry.</p>
                            <p class="track__card--desc">We are open to new partnerships and co-operation to create
                                profitable and scalable mining projects together.</p>
                        </div>
                    </div>
                </article>
            </li>

            <li class="track__item" data-slide="4" id="track-slide-4" aria-hidden="true">
                <article class="track__card" aria-labelledby="track-slide-4-title">
                    <div class="track__card--wrap">
                        <div class="progress-bar" data-percentage="5" role="img" aria-label="5 percent of total income">
                            <div class="progress-bar__circle" aria-hidden="true">
                                <div class="progress-bar__circle-fill"></div>
                                <div class="progress-bar__circle-inner">
                                    <div class="progress-bar__glow"></div>
                                </div>
                            </div>
                            <div class="progress-bar__text" aria-hidden="true">5%</div>
                        </div>

                        <div class="track__card--info">
                            <h3 class="track__card--title" id="track-slide-4-title">Investing in metals: stability and asset protection</h3>
                            <p class="track__card--desc">While metals investments don’t yield as high returns as other
                                areas, they are crucial for our asset preservation strategy. Unlike high-growth sectors
                                like blockchain or mining, metals provide stability and security for long-term
                                investments.</p>
                            <p class="track__card--desc">We consider metals the best way to protect capital, which is
                                why we allocate a portion of profits from our more lucrative sectors to this area. For
                                example, alongside a $5,000,000 investment in a new mining farm, we place an additional
                                $5,500,000 in precious metals, securing long-term stability for our funds.</p>
                            <p class="track__card--desc">Our approach balances risky and stable investments, sustaining
                                business growth and ensuring positive financial results. Ignoring capital preservation
                                by not investing in reliable assets risks financial instability.</p>
                            <p class="track__card--desc">We are confident that, with our metals investment strategy
                                (increasing by 10%), our business will remain stable and secure, unaffected by sector
                                fluctuations.</p>
                        </div>
                    </div>
                </article>
            </li>

            <li class="track__item" data-slide="5" id="track-slide-5" aria-hidden="true">
                <article class="track__card" aria-labelledby="track-slide-5-title">
                    <div class="track__card--wrap">
                        <div class="progress-bar" data-percentage="18" role="img" aria-label="18 percent of total income">
                            <div class="progress-bar__circle" aria-hidden="true">
                                <div class="progress-bar__circle-fill"></div>
                                <div class="progress-bar__circle-inner">
                                    <div class="progress-bar__glow"></div>
                                </div>
                            </div>
                            <div class="progress-bar__text" aria-hidden="true">18%</div>
                        </div>

                        <div class="track__card--info">
                            <h3 class="track__card--title" id="track-slide-5-title">Buying back shares from insurance companies</h3>
                            <p class="track__card--desc">We buy back shares from companies looking to sell due to urgent
                                financial needs, doubts about future prospects, or financial challenges. Partnering with
                                insurance companies selling such shares provides us with unique profit opportunities.
                            </p>
                            <p class="track__card--desc">Our experts are skilled at identifying profitable deals,
                                viewing these sales as a chance for high returns despite others’ uncertainties. These
                                stocks often belong to new companies with uncertain futures, which presents both risks
                                and opportunities.</p>
                            <p class="track__card--desc">In certain cases, we achieve returns of 20% to 200%, though we
                                carefully manage risk with stop orders at 18% to protect against market volatility. This
                                approach enables us to safely purchase and quickly sell shares, focusing on short-term
                                gains with managed risk, rather than long-term holding of these high-risk assets.</p>
                        </div>
                    </div>
                </article>
            </li>

            <li class="track__item" data-slide="6" id="track-slide-6" aria-hidden="true">
                <article class="track__card" aria-labelledby="track-slide-6-title">
                    <div class="track__card--wrap">
                        <div class="progress-bar" data-percentage="3" role="img" aria-label="3 percent of total income">
                            <div class="progress-bar__circle" aria-hidden="true">
                                <div class="progress-bar__circle-fill"></div>
                                <div class="progress-bar__circle-inner">
                                    <div class="progress-bar__glow"></div>
                                </div>
                            </div>
                            <div class="progress-bar__text" aria-hidden="true">3%</div>
                        </div>

                        <div class="track__card--info">
                            <h3 class="track__card--title" id="track-slide-6-title">Opening a franchised mining farm: co-operation and new opportunities</h3>
                            <p class="track__card--desc">We are open to cooperation and offer a unique opportunity to
                                franchise a mining farm. Previously focused on hosting services, we now invest in mining
                                farm creation alongside our partners, providing full technical support to ensure
                                stability and profitability.</p>
                            <p class="track__card--desc">In this partnership, we jointly earn from mining, with hosting
                                fees paid separately for transparent payments and a clear distinction between mining and
                                hosting profits.</p>
                            <p class="track__card--desc">Our technical team maintains each partner farm, minimizing
                                risks and maximizing efficiency. We anticipate hosting services will generate up to 3%
                                of revenue, adding a stable income source.</p>
                            <p class="track__card--desc">We are confident our franchise model will drive business growth
                                and stable profits for all involved.</p>
                        </div>
                    </div>
                </article>
            </li>
        </ul>

        <nav class="track__pagination" aria-label="Track record pagination">
            <div class="pagination" role="tablist" aria-label="Choose a slide">
                <button class="dot active" type="button" data-slide="1" role="tab"
                    aria-selected="true" aria-controls="track-slide-1" aria-label="Slide 1"></button>
                <div class="line" aria-hidden="true"></div>

                <button class="dot" type="button" data-slide="2" role="tab"
                    aria-selected="false" aria-controls="track-slide-2" aria-label="Slide 2"></button>
                <div class="line" aria-hidden="true"></div>

                <button class="dot" type="button" data-slide="3" role="tab"
                    aria-selected="false" aria-controls="track-slide-3" aria-label="Slide 3"></button>
                <div class="line" aria-hidden="true"></div>

                <button class="dot" type="button" data-slide="4" role="tab"
                    aria-selected="false" aria-controls="track-slide-4" aria-label="Slide 4"></button>
                <div class="line" aria-hidden="true"></div>

                <button class="dot" type="button" data-slide="5" role="tab"
                    aria-selected="false" aria-controls="track-slide-5" aria-label="Slide 5"></button>
                <div class="line" aria-hidden="true"></div>

                <button class="dot" type="button" data-slide="6" role="tab"
                    aria-selected="false" aria-controls="track-slide-6" aria-label="Slide 6"></button>
            </div>
        </nav>
    </div>

    <div class="shadow-bottom" aria-hidden="true"></div>
</section>


<script>
    document.querySelectorAll('.progress-bar').forEach(bar => {
        const percentage = bar.getAttribute('data-percentage');
        const targetAngle = (percentage / 100) * 360;
        const fill = bar.querySelector('.progress-bar__circle-fill');
        let currentAngle = 0;

        fill.style.background = 'linear-gradient(135deg, #5900f5, #8a2be2, #5900f5)';
        fill.style.backgroundSize = '300% 300%';
        fill.style.animation = 'gradient-shift 3s ease infinite';

        const animateProgress = () => {
            if (currentAngle < targetAngle) {
                currentAngle += 2;
                fill.style.maskImage = `conic-gradient(
                rgba(0, 0, 0, 1) 0deg ${currentAngle}deg,
                transparent ${currentAngle}deg 360deg
            )`;
                requestAnimationFrame(animateProgress);
            }
        };

        animateProgress();
    });
    document.addEventListener('DOMContentLoaded', () => {
        const slides = document.querySelectorAll('.track__item');
        const dots = document.querySelectorAll('.pagination .dot');
        let currentSlide = 0;

        const updateSlides = (index) => {
            slides.forEach(slide => slide.classList.remove('active'));
            dots.forEach(dot => dot.classList.remove('active'));

            slides[index].classList.add('active');
            dots[index].classList.add('active');
        };

        const nextSlide = () => {
            currentSlide = (currentSlide + 1) % slides.length;
            updateSlides(currentSlide);
        };

        const prevSlide = () => {
            currentSlide = (currentSlide - 1 + slides.length) % slides.length;
            updateSlides(currentSlide);
        };

        dots.forEach((dot, index) => {
            dot.addEventListener('click', () => {
                currentSlide = index;
                updateSlides(currentSlide);
            });
        });

        updateSlides(currentSlide);
    });
</script>
